#ifndef OPENU_PROJECT_CONSTS_H
#define OPENU_PROJECT_CONSTS_H

#define MAX_LINE_LENGTH 80
#define OPCODES_COUNT 16
#define REGISTER_COUNT 8
#define INSTRUCTIONS_COUNT 4
#define MAX_LABEL_LENGTH 31
#define MAX_OPCODE_LENGTH 4
#define MAX_ADDRESS_METHODS 4
#define MAX_BIN_LENGTH 15
#define PREPROCESSED_FILE_TYPE ".as"
#define PROCESSED_FILE_TYPE ".am"
#define FINAL_FILE_EXTENSION ".ob"
#define ENTERIES_FILE_EXTENSION_LEN 4
#define ENTERIES_FILE_EXTENSION ".ent"
#define EXTERNS_FILE_EXTENSION_LEN 4
#define EXTERNS_FILE_EXTENSION ".ext"
#define MAX_EXTENSION_LENGTH 5
#define MAX_DATA_NUM_VALUE 16383
#define MIN_DATA_NUM_VALUE -16384
#define MAX_COMMAND_NUM_VALUE 2047
#define MIN_COMMAND_NUM_VALUE -2048
#define IC_OFFSET 100

#endif

