#ifndef OPENU_PROJECT_CONSTS_H
#define OPENU_PROJECT_CONSTS_H

#define MAX_LINE_LENGTH 80
#define OPCODES_COUNT 16
#define REGISTER_COUNT 8
#define INSTRUCTIONS_COUNT 4
#define MAX_LABEL_LENGTH 31
#define MAX_OPCODE_LENGTH 4
#define MAX_ADDRESS_METHODS 4
#define MAX_BIN_LENGTH 15

#define PREPROCESSED_FILE_TYPE ".am"

#define IC_OFFSET 100

#endif //OPENU_PROJECT_CONSTS_H

