#ifndef OPENU_PROJECT_CONSTS_H
#define OPENU_PROJECT_CONSTS_H

#define MAX_LINE_LENGTH 80
#define OPCODES_COUNT 16
#define REGISTER_COUNT 8
#define INSTRUCTIONS_COUNT 4
#define SYMBOL_COUNT 6
#define MAX_LABEL_LENGTH 31

#define PREPROCESSED_FILE_TYPE ".am"

#define IC_OFFSET 100

#endif //OPENU_PROJECT_CONSTS_H

