name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
    - name: run test
      run: |
        make
        ./openu_project test_files/test
    - name: memory leak test
      run: |
        make
        valgrind ./openu_project test_files/test
