name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make
      - name: apt install dependency
        run: |
          sudo apt-get -y install valgrind
      - name: run test
        run: |
          make
          ./assembler test_files/valid_test1
      - name: memory leak test
        run: |
          make
          valgrind --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          --verbose \
          --error-exitcode=42 \
          ./assembler test_files/valid_test1 test_files/valid_test2
